[package]
name = "climsg-server"
version = "0.1.0"
edition = "2021"

[dependencies]
climsg-core = { path = "../climsg-core" }

async-io = "1.13.0"
dashmap = "5.4.0"
serde_json = "1.0.97"
tokio = { version = "1.28.2", features = ["sync"] }
