[package]
name = "climsg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.9", features = ["derive", "wrap_help"] }
climsg-core = { path = "../climsg-core" }

serde_json = "1.0.97"
